apiVersion: apps/v1
kind: Deployment
metadata:
  name: gps-course-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gps-course-demo
  template:
    metadata:
      labels:
        app: gps-course-demo
    spec:
      containers:
      - name: gps-course-demo
        #image: ghcr.io/manjunathmbn/gps-course-demo:latest
        image: gpscoursedemo.azurecr.io/course:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
